export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  FORBIDDEN = 'FORBIDDEN',
  PRISMA_CONSTRAINT = 'PRISMA_CONSTRAINT',
  PRISMA_NOT_FOUND = 'PRISMA_NOT_FOUND',
  PRISMA_FOREIGN_KEY = 'PRISMA_FOREIGN_KEY',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}
